katalyst/koi

koi.gemspec, lib/templates/application/app.rb
- Removed Spring, as no one uses it currently, and it causes various errors
- Updated branch of koi written to the gemfile in bootstrap process
- Specified specific version of Airbrake gem which we know to be stable (used on ysa-v2)
- Specific a specific commit of i18n-active_record gem that we believe to be stable
=> fixed several gem versions that were holding up bootstrapping

lib/has_crud/has_crud/action_controller/admin/crud_methods.rb
Previously it was trying to sorted all instances of a model, even if it was a nested route. For example, with categories and products, ordering sink products in the sink category was screwing with the ordering of taps in the tap category.
=> fixed sort method so it works for nested resources

app/assets/javascripts/koi/application.js, app/assets/javascripts/koi/koi/wysiwyg.js, app/views/koi/admin_crud/_form_field_inline.html.erb
* Removed sticky CKEditor toolbar as per #259
* Removed reinitialisation of CKEditor when opening/closing inline nested groups. 
* Removed reinitialisation of CKEDitor when changing tabs
* Updated the `wysiwyg()` function to only initialise on CKEditors that aren't already initialised, rather than nuking them all then initialising them all again. 
* Fixed adding a new inline nested group not initialising newly added CKEditors immediately 
* Improved UX of adding inline nested groups by collapsing other inline nested items. This reflects the behaviour of toggling them open/closed which only allows one open at a time. Not related to CKEditor but an easy fix while I was there.
=> CKEditor Fixes (#259)

app/assets/stylesheets/koi/components/_island.scss
Inherited resources uses notice (success) and alert(error) by default. You can override these in config but only for respond_to. Respond_with with use only the defaults.
=> Issue 225 - Fixed flash message colour on success

app/helpers/koi/application_helper.rb
Fixes https://github.com/katalyst/koi/issues/273 (using option a)
> Often we use non-database fields in our koi listing pages, e.g.
```ruby
index fields: [:full_name]
def full_name
first_name + " " + last_name
end
```
> Ordering by this column in the UI doesn't work at the moment. We should either (a) disable ordering for non-database fields, or (b) implement ordering for these fields (which would be a lot more work, and would be a bad idea for tables that have a very large number of records, since you'd have to do the sorting in Ruby.)
=> Removed sorting on non-database columns in index view [#273]

app/assets/javascripts/koi/components/navigation-mobile.js, app/assets/javascripts/koi/components/shortcuts.js, app/assets/javascripts/koi/ornament/defaults.js, app/assets/stylesheets/koi/components/_layout.scss, app/assets/stylesheets/koi/components/_navigation-mobile.scss, app/views/layouts/koi/global.html.erb, lib/koi/menu.rb
Discussion: https://github.com/katalyst/koi/issues/274
* Fuzzy search using (using [this technique](https://github.com/bevacqua/fuzzysearch/blob/master/index.js))
* Filter automatically focuses when opening the menu, ready to be filtered
* Results show a breadcrumb-style helper to indicate what folders the result is in  
* When filtering, tabindices are regenerated so you can quickly tab down to your results 
Just building a small site that wouldn't warrant a menu filter? No worries! 
```ruby
Koi::Menu.filterable = false
```
=> Added filter to slide-out menu

app/assets/javascripts/koi/components/enhanced-form.js, app/views/koi/admin_crud/_form_field.html.erb, test/dummy/app/models/super_hero.rb
You can now customise your `:date` or `:datetime` fields with (almost) any option available in either API.
```ruby
published_at: { type: :date, datepicker: { dateformat: "dd M yy", maxdate: "0" } }
```
Options available are listed in the `enhanced-form.js` file and should cover off any basic settings. Anything more advanced such as custom callbacks and whatnot would probably warrant a custom field type.
=> Custom datepicker settings in crud config

app/assets/javascripts/koi.js, app/assets/javascripts/koi/nav_items.js, app/views/koi/nav_items/_nav_item.html.erb, vendor/assets/javascripts/koi/store.js
Now when a user closes a navitem in the sitemap it will remember their selections in localStorage and reflect this when they come back to the sitemap next time. 
As part of this, I rewrote the `nav_items.js` to be much more readable and exposed some public functions to the `Ornament.C` API:
```js
// See all the commands available
Ornament.C.Sitemap
// Debugging
Ornament.C.Sitemap.logging = true; // will turn on logging to output debug info to the console
// Read from user local storage
Ornament.C.Sitemap.getLockedStateFromLocalStorage(); // find out if the sitemap is locked or not
Ornament.C.Sitemap.getClosedNodesFromLocalStorage(); // get array of currently closed nodes
Ornament.C.Sitemap.setClosedNodesInLocalStorage([1,2,3]); // update local storage closed nodes
// Drag and drop states …
```
=> Remember which sitemap nodes were toggled open/closed

app/assets/javascripts/koi/components/select-link.js, app/views/kaminari/admin/_paginator.html.erb, app/views/koi/admin_crud/_index_pagination_options.html.erb, app/views/koi/admin_crud/index.js.erb
On desktop you get all pagination options, page links, first, previous, next and last. 
On mobile the next and previous links are retained and the pages are removed and only the next and previous links remain. 
I've improved the UX by adding a hidden select menu on mobile so that when you click on "Page X of Y" you can easily jump to another page:
On the technical side, Kaminari has a [page_url_for(page) helper](https://github.com/kaminari/kaminari/blob/master/kaminari-core/lib/kaminari/helpers/tags.rb#L35) but it would not work, so I've kind of munged together the resultant URL. It works, but it feels weird to build up my own URL rather than get it from Kaminari.
=> Mobile Pagination Select Menu

app/assets/javascripts/koi/nav_items.js, app/views/koi/nav_items/_nav_item.html.erb
* Refactored the Sitemap JS code a little bit to expose more public functions and allow for showing all / hiding all. 
* Added two buttons that appear when hovering over the Navigation Groups container that show all and hide all nodes. 
* The two buttons conditionally appear / disappear based on wether they are needed or not. Eg. Show all disappears when all nodes are already visible.
=> Open all / Close all on Sitemap

app/assets/javascripts/koi/components/enhanced-form.js, app/assets/stylesheets/koi/components/_devise.scss, app/assets/stylesheets/koi/components/_form.scss, app/views/admins/passwords/edit.html.erb, app/views/admins/passwords/new.html.erb, app/views/admins/sessions/new.html.erb, app/views/layouts/koi/_icons.html.erb, app/views/layouts/koi/devise.html.erb, app/views/layouts/koi/global.html.erb
Updated devise views (login, forgot password) to match redesign.
For testing purposes, temporarily disable the autologin:
```ruby
before_filter :sign_in_as_admin! if Rails.env.development?
```
RFC: https://github.com/katalyst/koi/issues/291
=> Redesigned Devise Views

app/controllers/koi/translations_controller.rb, app/views/koi/application/_google_analytics.html.erb, db/seeds.rb, test/dummy/app/views/layouts/application.html.erb, test/dummy/app/views/layouts/mobile/application.html.erb
Removed default values for:
* Site Title
* Meta Description
* Meta Keywords
* Google Analytics Profile ID
* Twitter Search Query
Outright removed these default settings:
* Google Analytics Embed Script
- Removed in favour of only using the Profile ID as the hook to add the script to the front-end
* Show Google Analytics 
- This was being used as a flag to show the Google Analytics dashboard reports. 
* Google Analytics Username
- Was being used for the dashboard analytics
* Google Analytics Password
- Was being used for the dashboard analytics
I've removed the Google Analytics dashboard view code as well since it's broken and no longer being used. It will be improved in the future with the Dashboard upgrade. 
See this RFC for more info:
https://github.com/katalyst/koi/issues/324
It's …
=> 324 - Better Default Site Settings

app/views/kaminari/admin/_first_page.html.erb, app/views/kaminari/admin/_gap.html.erb, app/views/kaminari/admin/_last_page.html.erb, app/views/kaminari/admin/_next_page.html.erb, app/views/kaminari/admin/_prev_page.html.erb, config/initializers/kaminari_config.rb, config/locales/en.yml
Fixes #307 
* Increased specificity of Koi language settings for pagination so that the application doesn't override Koi's (eg. uses `views.koi.pagination.first` rather than `views.pagination.first`)
* added kaminari initialiser to set outside_window to 1 so that first and last page numbers are shown
=> #307 - Pagination Fixes

app/views/koi/settings/_field_file.html.erb, app/views/koi/settings/_field_image.html.erb
Fixed the browse `button` element sitting over the label/hint for image/file uploads in settings.
=> Settings: Image/File uploads alignment issue

lib/templates/application/app.rb
Just a quick one to fix the generated `pages_controller.rb` inheriting from `Koi::CrudController` rather than `CrudController`.
=> Missing CommonControllerActions in PagesController

app/assets/stylesheets/koi/nav_items.scss, app/models/folder_nav_item.rb, app/models/module_nav_item.rb, app/models/nav_item.rb, app/models/resource_nav_item.rb, app/views/koi/nav_items/_nav_item.html.erb, app/views/koi/shared/icons/_links_to_child.html.erb, db/migrate/20170915073755_add_link_to_child_to_nav_item.rb, test/dummy/db/migrate/20170915073755_add_link_to_child_to_nav_item.rb
We have a common use-case where we have top-level navigation that actually links to the first of their child navigation, eg:
```
about_us - this actually links to the 'about_us' below
about_us
our team
contact us
```
Normally we solve this by creating a module navitem with a URL pointing to the first child navitem.   
That solution works okay but it's not very flexible and can be confusing for some people.   
This solution adds a "Link to first child" tick-box in the navitem modify menu, which automatically overrides the url passed in to simple form as the first child url instead. 
The sitemap shows a handy-dandy icon to represent redirected navitems:
I made the conscious decision to not add this to alias navitems, since the alias navitem is already all about redirecting. It might be …
=> Sitemap - Link navitem to first child

app/views/koi/admin_crud/_form_field_nice_tags.html.erb, test/dummy/app/models/product.rb
- it should no longer merge tags after saving
- autocomplete should now work regardless of the name of your tag field
=> fixed nice_tags field type for rails 4 & new acts_as_taggable version

lib/templates/application/app.rb
* The release of postgres 1.0.0 has broken `rails new -d postgres`
* The pg gem is added to the gemfile via the `rails new` command, it's not something added by Koi
* Tried adding `'pg', '0.21'` as another gem in app.rb, that results in two pg gems and bundle won't bundle
* Tried locking pg's gem version in Koi's Gemfile.lock or specifying the version in Koi's gemspec, didn't have any affect on the resulting Gemfile, it always resulted in just `gem 'pg'` which bundled to version 1.0.0
* I couldn't find any method of overriding the postgres version that gets generated, the best option I could find was to gsub replace during bootstrap
=> Fix for postgres 1.0.0 release breaking bootstrapping process

lib/templates/application/app.rb, test/dummy/config/initializers/setup_smtp.rb
Mailtrap has switched SMTP domain from `mailtrap.io` to `smtp.mailtrap.io`
=> Switching to new mailtrap domain

app/models/concerns/composable.rb, lib/koi/composable_components.rb
When creating a composition without using any sections, the composition on the front-end is wrapped in a default section, currently named "body".
If a developer overrides the section component to customise the list of sections and *doesn't* have a body section, the body section can get in the way.
For example, you might override the section list to be something like, `["large", "medium", "small"]`
This change provides a way to customise the name of the fallback section in the initailizer using:
```
Koi::ComposableContent.set_fallback_section_type "medium"
```
=> Composable - Define fallback section name

app/views/koi/admin_crud/index.html.erb, lib/has_crud/has_crud/action_controller/admin/crud_methods.rb
The record count above search currently shows the total number of records in the table, rather than the current result set. 
This change should fix that.
=> fixed count to be accurate for nested resources and for search results

app/assets/javascripts/koi.js, app/assets/javascripts/koi/components/form-managed-asset.js, app/models/concerns/has_managed_assets.rb, app/views/koi/admin_crud/_form_field_managed_document.html.erb, app/views/koi/admin_crud/_form_field_managed_image.html.erb, lib/has_crud/has_crud/active_record.rb, test/dummy/app/models/kid_hero.rb, test/dummy/db/migrate/20181214012206_add_managed_assets_to_super_hero.rb, test/dummy/db/schema.rb
New form field type for uploads via the asset manager.
```ruby
include HasManagedAssets
managed_image :banner_image # banner_image_asset_id
managed_document :case_study # case_study_asset_id
crud.config do
fields banner_image: { type: :managed_image },
case_study:   { type: :managed_document }
end
```
The `KidHero` model has been updated with a demo of a managed asset and a managed document.
=> Managed asset field type

app/assets/stylesheets/koi/components/_composable.scss, app/assets/stylesheets/koi/components/_tabs.scss, app/models/concerns/composable.rb, app/views/koi/admin_crud/_form_field_composable.html.erb, spec/dummy/app/frontend/javascripts/koi/Composable/Composable.jsx, spec/dummy/app/frontend/javascripts/koi/Composable/ComposableComponent.jsx, spec/dummy/app/frontend/javascripts/koi/Composable/ComposableComposition.jsx, spec/dummy/app/frontend/javascripts/koi/Composable/ComposableGroupItem.jsx, spec/dummy/app/models/page.rb, spec/dummy/app/views/pages/show.html.erb
Creating more than one composable content section on a single record / view.
Say you want a composable content in a sidebar and another in the main area of the page.
This isn't currently possible without hacks or abusing the sectioning component
For reference, currently the composable config in the model looks like this:
```ruby
composable: [
:component_1,
:component_2,
:component_3,
]
```
And the output of the composable content JSON is similar:
```js
components: [{
component_type: "component_1",
data: [{
field1: value,
field2: value,
}]
}]
```
This change proposes a change to both the crud config and the output:
```ruby
composable: {
main: [
:component_1,
:component_2,
:component_3,
],
sidebar: [
:component_2,
:component_4,
:component_5,
]
}
```
```js
components: [{
main: [{ …
```
=> Composable Content Groups

app/assets/javascripts/koi/components/form-inline-nested.js, app/assets/javascripts/koi/components/form-managed-asset.js
the managed asset javascript was only binding on ornament:refresh, so when new inline
repeater items were created after clicking, say, "Add Banner", no event
handlers were being added to button so it was doing nothing
We'll need to do a release commit to bump the version after merging this, and upgrade Tonkin.
=> TCW-202 - fixed managed image buttons in repeaters

app/helpers/koi/navigation_helper.rb
workaround for simple navigation bug. rendering nav causes nav options to be deleted, including :if lambda procs. AIT uses nav :if lambda procs to hide nav items depending on whether a user is logged in. AIT renders two navigations (desktop and mobile). The second nav to be rendered (mobile) does not include the :if lambda procs. So the mobile nav shows items it shouldn't.
This change removes the in-memory cache of navigation configuration, so options are regenerated each time navigation is rendered.
=> Remove in-memory nav config cache

app/models/nav_item.rb
adds 'data-nav-item-type' to the html output by simple navigation. This can be used by renderers to customise navigation based on the type of navigation items.
The motivation for this comes from the SATAC project, where we want to apply different styles to navigation items that have all direct descendants as 'Folder' navigation items.
=> Expose nav item type to renderer

lib/koi/engine.rb
This is necessary for the url redirects to work
=> Insert UrlRedirect before Rack::Sendfile

app/helpers/koi/icon_helper.rb
.jpg extensions are considered as file type by dragonfly and hence .thumb cannot be achieved
=> Fix .jpg extension error for attachments on oliveri

lib/koi/engine.rb
* This was present in previous versions of Koi but was removed during Rails6 upgrade
=> Fix: Insert UrlRewrite middleware before Rack::Sendfile

app/models/document.rb
Update for release/2.4 branch. Can probably be added to release/2.5 branch also.
Changed document url to be /documents/:id instead of linking directly to s3.
Matches behaviour of images.
=> SAT-184: Use vanity urls for documents

CHANGELOG.md, app/helpers/koi/navigation_helper.rb, app/models/alias_nav_item.rb, app/models/folder_nav_item.rb, app/models/module_nav_item.rb, app/models/nav_item.rb, app/models/resource_nav_item.rb, app/models/root_nav_item.rb, app/views/koi/nav_items/_advanced_form_fields.html.erb, app/views/koi/nav_items/_god_form_fields.html.erb, app/views/koi/nav_items/_modal_nav_item.html.erb, app/views/layouts/koi/_navigation_item.html.erb, db/migrate/20220330104437_remove_nav_item_eval_fields.rb, spec/dummy/db/schema.rb
NavItem previously supported runtime eval for customising navigation
menus, but this was inherently un-cacheable and has not been possible
to edit these fields since v2.2.0 when caching was added (2016).
This commit adds a migration to remove the attributes and the runtime
eval implementation, which allows for a significant code cleanup.
=> Remove NavItem eval attributes

Gemfile.lock, app/views/koi/assets/_listing.html.erb, lib/has_navigation/has_navigation/has_navigation.rb
With turbo enabled, `koi/koi/assets.js` is not loading in the **assets -> show** page. This JS file is responsible for calling the `ckeditor` callback & for closing the popup.
=> FRIN23-107: Exclude turbo from handling links in asset listing

app/controllers/koi/url_rewrites_controller.rb, app/models/admin_user.rb, app/models/url_rewrite.rb, app/views/koi/url_rewrites/_form_fields.html.erb, app/views/koi/url_rewrites/edit.html.erb, app/views/koi/url_rewrites/index.html.erb, app/views/koi/url_rewrites/new.html.erb, app/views/koi/url_rewrites/show.html.erb, spec/factories/url_rewrites.rb, spec/models/url_rewrite_spec.rb, spec/requests/koi/url_rewrites_controller_spec.rb
- Adds `Archivable` concern from FRG to KOI - Not sure if it's a good idea
- Minor concern : Should we support paths without a leading backlash? Or add validation to start with backlash? 
```ruby
def self.redirect_path_for(path)
not_archived.find_by(from: path).try(:to)
end
```
- Uses `delete_prefix` to remove leading backlash for breadcrumbs
FRG changes -> https://github.com/katalyst/frg/tree/refactor/FRIN23-627-admin-crud
=> FRIN23-627: Refactor Admin UrlRewriteController

app/views/koi/shared/icons/_close.html.erb
* This was removed in the commit `143874c23acbac93e6bd94c7a4f86abc9c0e7c98` but is referenced from flash_messages partial
* Sentry error ref from fringe: `https://adelaide-fringe.sentry.io/issues/3955840032/?environment=staging&project=5431524&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h`
=> Add close icon

app/assets/javascripts/koi/controllers/navigation_controller.js, app/views/layouts/koi/application.html.erb
Improves navigation with prefix search, e.g. "vs" will match "View Site" but not "Previews". This is similar to the type of search used in JetBrains products that we're used to.
Also changes on-page search shortcut to use `/` instead of `\`.
=> Navigation prefix search

lib/koi/release.rb
* Ruby 3.2 has removed the support for `.exists?` and this can fixed to use `.exist?` instead
=> Remove and replace `File.exists?` usage

config/routes.rb, lib/koi/menu.rb
mounting the engines causes the "engine_name" to be prefixed with the namespace. So `katalyst_content.root_path` would resolve to `admin_katalyst_content.root_path`. This causes issues as internally in the engines they refer to `katalyst_content` etc.
Moving the mount into a scope so it only affects the route not the helper generator
=> Fix - Content and Navigation engine namespaced to admin

config/locales/pagy.en.yml
=> Fix: Missing translation for pagy gap

lib/tasks/dummy.thor
If a developer has configuration for projects in (e.g.) a .railsrc file that sets a different database, the generator will fail as the adapter is not included in the template. We can remediate this issue by explicitly setting sqlite3 as the database when setting up the dummy application.
=> Fix: Explicitly set the database for the dummy app to sqlite3

app/assets/stylesheets/koi/components/_index.scss, app/assets/stylesheets/koi/components/_summary-list.scss, app/components/koi/summary_list/base.rb, app/components/koi/summary_list/boolean_component.rb, app/components/koi/summary_list/date_component.rb, app/components/koi/summary_list/datetime_component.rb, app/components/koi/summary_list/item_component.rb, app/components/koi/summary_list/number_component.rb, app/components/koi/summary_list/rich_text_component.rb, app/components/koi/summary_list/text_component.rb, app/components/koi/summary_list_component.html.erb, app/components/koi/summary_list_component.rb, app/helpers/koi/definition_list_helper.rb, lib/generators/koi/admin_views/admin_views_generator.rb, lib/generators/koi/admin_views/templates/show.html.erb.tt, spec/components/koi/summary_list/boolean_component_spec.rb, spec/components/koi/summary_list/date_component_spec.rb, spec/components/koi/summary_list/datetime_component_spec.rb, spec/components/koi/summary_list/item_component_spec.rb, spec/components/koi/summary_list/number_component_spec.rb, spec/components/koi/summary_list/rich_text_component_spec.rb, spec/components/koi/summary_list/text_component_spec.rb, spec/components/koi/summary_list_component_spec.rb, spec/generators/koi/admin_views_generator_spec.rb
Update summary component for show pages to allow users to declaratively specify the types they are expecting.
Supersedes and deprecates the existing `definition_list` helper.
=> Summary component

app/assets/javascripts/koi/controllers/clipboard_controller.js, app/assets/stylesheets/koi/components/_clipboard.scss, app/assets/stylesheets/koi/components/_index.scss, app/assets/stylesheets/koi/pages/_login.scss, app/controllers/admin/tokens_controller.rb, app/controllers/concerns/koi/controller/json_web_token.rb, app/models/admin/user.rb, app/views/admin/admin_users/show.html.erb, app/views/admin/sessions/new.html.erb, app/views/admin/tokens/create.turbo_stream.erb, app/views/admin/tokens/show.html.erb, config/routes.rb, spec/requests/admin/tokens_controller_spec.rb, spec/system/admin/invitation_spec.rb
* Adds new endpoint to handle invitations
* Enables generating invitation link to share from admin user show page
* Adds a signup page using token details
* updates validations on password, so that password is optional
**Invitation link**
**show page**
=> Generate invitations to enrol new admin users

app/controllers/koi/settings_controller.rb, app/views/koi/settings/_field_boolean.html.erb, app/views/koi/settings/_field_check_boxes.html.erb, app/views/koi/settings/_field_dynamic.html.erb, app/views/koi/settings/_field_file.html.erb, app/views/koi/settings/_field_radio.html.erb, app/views/koi/settings/_field_rich_text.html.erb, app/views/koi/settings/_field_select.html.erb, app/views/koi/settings/_field_string.html.erb, app/views/koi/settings/_field_text.html.erb, app/views/koi/settings/_form_fields.html.erb, app/views/koi/settings/_settings_form.html.erb
related to https://github.com/heartcombo/simple_form/issues/1834 The previous html for editing a setting looked like this:
```
<input class="string optional form--medium enhanced" type="text" name="setting[setting[36086]][value]" id="setting_setting_70243__value">
```
it now looks like:
```
<input value="Job position" class="string required form--medium enhanced" type="text" name="setting[setting_36086][value]" id="setting_setting_36086_value">
```
=> Fix for editing settings with simple form and rails 7.1 (Koi 2.6)

app/views/layouts/koi/_navigation_header.html.erb
When viewing the navigation module (Navigation Engine) it could not resolve the `admin_admin_user_path`. 
Using `main_app` allows both the mounted engines (navigation, content) and koi to resolve the `admin_admin_user_path` correctly
=> Fix: named route helpers when viewing mounted engines

config/initializers/navigation.rb, lib/govuk_design_system_formbuilder/elements/document.rb
Resolves https://github.com/katalyst/koi/issues/590
I note that we also do not have any tests for these custom elements. This would be something to consider, too.
=> Allow accept attribute override via mime_types keyword argument

Gemfile.lock, app/helpers/koi/index_actions_helper.rb, spec/system/index/filtering_spec.rb
If you typed while the response of the search is being rendered turbo morph would clobber your input field to display what was sent to the server, not your latest changes. Marking the input field as permanent ensures the user can continue typing.
=> Index search - clobbering as you typed

Gemfile.lock, app/views/katalyst/navigation/menus/edit.html.erb, katalyst-koi.gemspec
Removal of `admin_save` caused the button to not have a `commit` param, skipping the save of the menu.
=> Save navigation menu on edit
